name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
    - add-cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Use Node.js 10.x
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: 10.x

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Prepare and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm run ng -- deploy --base-href=/BackPackManager/ --name="KubaMiszcz" --email="zielonyeufor@gmail.com" --no-silent